version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies & Build
          command: yarn
      - run:
          name: Publish Canary
          command: |
            if [ "${CIRCLE_PR_USERNAME}" == "" ]
            then
                echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
                npm run ci:release:canary
            else    
                echo "Skipping canary publish due to a fork PR..."
            fi
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules